version: "3.9"
services:
  plex:
    image: greensheep/plex-server-docker-rpi:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /your_media_folder/plex/config:/config #set this to your media folder
      - /you_media_folder:/data #set this to your media folder
    restart: unless-stopped
